name: Build and Publish Docker Image


on:
  push:
    branches:
      - main
    paths:
      - 'scripts/entry.sh'
      - 'scripts/search_folder.sh'
      - 'scripts/resolve_workshop_collection.sh'
      - 'scripts/get_latest_versions.sh'
      - 'Dockerfile'
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO_NAME=${{ github.repository }}
          echo "REPO_NAME_LC=${REPO_NAME,,}" >>${GITHUB_ENV}

      - name: Set repo version
        run: |
          echo "REPO_VERSION=${GITHUB_SHA::7}" >>${GITHUB_ENV}

      - name: Get latest Project Zomboid versions
        run: |
          chmod +x scripts/get_latest_versions.sh
          scripts/get_latest_versions.sh >> ${GITHUB_ENV}
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}

      - name: Decide which images to build
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "BUILD_STABLE=true" >> ${GITHUB_ENV}
            echo "BUILD_UNSTABLE=true" >> ${GITHUB_ENV}
          else
            BUILD_STABLE=false
            BUILD_UNSTABLE=false

            if ! docker manifest inspect ghcr.io/$REPO_NAME_LC:stable-${LATEST_STABLE_VERSION} >/dev/null 2>&1; then
              BUILD_STABLE=true
            fi

            if ! docker manifest inspect ghcr.io/$REPO_NAME_LC:unstable-${LATEST_UNSTABLE_VERSION} >/dev/null 2>&1; then
              BUILD_UNSTABLE=true
            fi

            echo "BUILD_STABLE=${BUILD_STABLE}" >> ${GITHUB_ENV}
            echo "BUILD_UNSTABLE=${BUILD_UNSTABLE}" >> ${GITHUB_ENV}
          fi

      - name: Build stable Docker image
        if: env.BUILD_STABLE == 'true'
        run: |
          docker build \
            -t ghcr.io/$REPO_NAME_LC:latest \
            -t ghcr.io/$REPO_NAME_LC:stable-${LATEST_STABLE_VERSION} \
            -t ghcr.io/$REPO_NAME_LC:stable-${LATEST_STABLE_VERSION}-${REPO_VERSION} \
            -t ghcr.io/$REPO_NAME_LC:stable \
            .

      - name: Build unstable Docker image
        if: env.BUILD_UNSTABLE == 'true'
        run: |
          docker build \
            --build-arg STEAMAPPBRANCH=unstable \
            -t ghcr.io/$REPO_NAME_LC:latest-unstable \
            -t ghcr.io/$REPO_NAME_LC:unstable-${LATEST_UNSTABLE_VERSION} \
            -t ghcr.io/$REPO_NAME_LC:unstable-${LATEST_UNSTABLE_VERSION}-${REPO_VERSION} \
            -t ghcr.io/$REPO_NAME_LC:unstable \
            .

      - name: Push stable Docker image to GitHub Container Registry
        if: env.BUILD_STABLE == 'true'
        run: |
          docker push ghcr.io/$REPO_NAME_LC:latest
          docker push ghcr.io/$REPO_NAME_LC:stable-${LATEST_STABLE_VERSION}
          docker push ghcr.io/$REPO_NAME_LC:stable-${LATEST_STABLE_VERSION}-${REPO_VERSION}
          docker push ghcr.io/$REPO_NAME_LC:stable

      - name: Push unstable Docker image to GitHub Container Registry
        if: env.BUILD_UNSTABLE == 'true'
        run: |
          docker push ghcr.io/$REPO_NAME_LC:latest-unstable
          docker push ghcr.io/$REPO_NAME_LC:unstable-${LATEST_UNSTABLE_VERSION}
          docker push ghcr.io/$REPO_NAME_LC:unstable-${LATEST_UNSTABLE_VERSION}-${REPO_VERSION}
          docker push ghcr.io/$REPO_NAME_LC:unstable
